spring:
  servlet:
    multipart:
      max-file-size: 100MB
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.198.135:3306/CPMS_MMAT?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 5000
      phy-timeout-millis: 7200000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      validation-query: SELECT 1
      validation-query-timeout: 1
      time-between-eviction-runs-millis: 15000
      default-auto-commit: true
      log-abandoned: false
      connection-properties: socketTimeout=30000;connectTimeout=10000
  redis:
    host: 47.97.198.135
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-wait: 3s
        min-idle: 2
    timeout: 60s
  rabbitmq:
    host: rabbitmq.component.cpms
    port: 5672
    username: guest
    password: '{cipher}cd9658d7338b3215f999d811ee725d2b3d6458c7f2c44f21f871c68faca5511d'
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
ribbon:
  readTimeout: 30000
  socketTimeout: 30000
  connectTimeout: 30000
feign:
  hystrix:
    enabled: false
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 10000
          timeout:
            enabled: false
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml,classpath*:/mybatis-mappers/**/*.xml,classpath*:/templet-mappers/**/*.xml,classpath*:/extra-mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.chinamobile.cmss.cpms.user.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID"; 5:"全局唯一ID (字符类型唯一ID)",
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #是否自动刷新 Mapper 对应的 XML 文件,生产环境须关闭
    refresh: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: cpms_
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
##############################################################################
#认证授权配置
security:
  oauth2:
    client:
      clientId: cpms-client-browser
      clientSecret: cpms-client-browser-secret
      access-token-uri: http://auth.common.cpms:2000/oauth/token
      user-authorization-uri: http://auth.common.cpms:2000/oauth/authorize
    resource:
      user-info-uri: http://auth.common.cpms:2000/user
      prefer-token-info: false
      jwt:
        key-uri: http://auth.common.cpms:2000/oauth/token_key
      id: cpms-resource-user

cpms:
  oauth2:
    jwtSigningKey: cpms-a2bab0bcada1436aa7bd9f4748da2425
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
  excel-import:
    temp:
      local-dir: /app/cpms/temp/
##############################################################################